# This file was generated by GoReleaser. DO NOT EDIT.
cask "claunch" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "f2960e8d82f0966cb451b4b2187265a382fe3871b5371edba972e36a531f0b70"
      url "https://github.com/cameronsjo/claunch/releases/download/v#{version}/claunch_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8706f9dac4a845a473f129fb58cd1a0977b9445fdd3810e53e997c57bde064a5"
      url "https://github.com/cameronsjo/claunch/releases/download/v#{version}/claunch_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d5afcbdec6fe36c834499bd9536f4874f20782383b93d32e740e48c788880cc8"
      url "https://github.com/cameronsjo/claunch/releases/download/v#{version}/claunch_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "63028c3b885cac293c6803445afeb8f1038dd087660a28cbb11d5c0d35cb9ac9"
      url "https://github.com/cameronsjo/claunch/releases/download/v#{version}/claunch_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claunch"
  desc "Per-project launcher for Claude Code — cwd-resolved profiles, guided launch, then exec claude"
  homepage "https://github.com/cameronsjo/claunch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claunch"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claunch"]
    end
  end

  # No zap stanza required

end
