# This file was generated by GoReleaser. DO NOT EDIT.
cask "forgectl" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/forgectl"]
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/forgectl-bless-helper"]
    end
  end

  version "0.39.0"

  on_macos do
    on_arm do
      sha256 "c73c3a01d851220ba29770ddd1437e211b64a17074bd0a81a58f084084370995"
      url "https://github.com/cameronsjo/forgectl/releases/download/v#{version}/forgectl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "aa5c1f06700fe044c932feac41bba6d31a9e47e3d919f30fce9a49715aed57aa"
      url "https://github.com/cameronsjo/forgectl/releases/download/v#{version}/forgectl_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "forgectl"
  desc "Personal tmux/dev-experience CLI for the headless workbench (supersedes the bash `s` script)"
  homepage "https://github.com/cameronsjo/forgectl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forgectl"
  binary "forgectl-bless-helper"

  # No zap stanza required
end
