# This file was generated by GoReleaser. DO NOT EDIT.
cask "forgectl" do
  version "0.14.1"

  on_macos do
    on_arm do
      sha256 "2eb498ce501f011bc2ac0ec88814df264a86b8b5560e7eff5c0f24accf90258a"
      url "https://github.com/cameronsjo/forgectl/releases/download/v#{version}/forgectl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "10fbaae4dbfe5772c4cf91b10fc16968d4338f519c9f380d06ad25292be77990"
      url "https://github.com/cameronsjo/forgectl/releases/download/v#{version}/forgectl_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "forgectl"
  desc "Personal tmux/dev-experience CLI for the headless workbench (supersedes the bash `s` script)"
  homepage "https://github.com/cameronsjo/forgectl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forgectl"
  binary "forgectl-bless-helper"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/forgectl"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/forgectl-bless-helper"]
    end
  end

  # No zap stanza required
end
