# This file was generated by GoReleaser. DO NOT EDIT.
cask "forgectl" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "0b072dc6edf321d462d6e7a9844bab6f402a1959a8761441a3364426281bde13"
      url "https://github.com/cameronsjo/forgectl/releases/download/v#{version}/forgectl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "86a613cdabad7e21155cd154770641ffbfb6a0c6e10f9a9220d4889dbe2d04b0"
      url "https://github.com/cameronsjo/forgectl/releases/download/v#{version}/forgectl_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "forgectl"
  desc "Personal tmux/dev-experience CLI for the headless workbench (supersedes the bash `s` script)"
  homepage "https://github.com/cameronsjo/forgectl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forgectl"
  binary "forgectl-bless-helper"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/forgectl"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/forgectl-bless-helper"]
    end
  end

  # No zap stanza required

end
