# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoUnifiMcp < Formula
  desc "MCP server for UniFi Network Controller"
  homepage "https://github.com/cameronsjo/go-unifi-mcp"
  version "0.3.1"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cameronsjo/go-unifi-mcp/releases/download/v0.3.1/go-unifi-mcp_darwin_amd64.tar.gz"
      sha256 "0c496cdf3fa6124d49f027fcb3c2c411ce3ae73ed3627cdb535bc880d8903fc5"

      def install
        bin.install "go-unifi-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cameronsjo/go-unifi-mcp/releases/download/v0.3.1/go-unifi-mcp_darwin_arm64.tar.gz"
      sha256 "c7899655101293c875183059a48aa8bafef6047efbd621c2e295f6e5f3a92611"

      def install
        bin.install "go-unifi-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cameronsjo/go-unifi-mcp/releases/download/v0.3.1/go-unifi-mcp_linux_amd64.tar.gz"
      sha256 "fc114420171ca3f6eaede206821a8d10f7eb8928c4be5e1454228d5b2a433fda"
      def install
        bin.install "go-unifi-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cameronsjo/go-unifi-mcp/releases/download/v0.3.1/go-unifi-mcp_linux_arm64.tar.gz"
      sha256 "c83220b89836bd0689ee8633fd3690fb776f2ee0492edb5d9d31d80733881892"
      def install
        bin.install "go-unifi-mcp"
      end
    end
  end

  test do
    system "#{bin}/go-unifi-mcp", "--help"
  end
end
